datasource:
  db:
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: jdbc:postgresql://${JDBC_DATABASE_HOST}:${JDBC_DATABASE_PORT}/${JDBC_DATABASE_DATABASE}

ebean:
  #  ddl:
  #    run: true
  #    generate: true
  migration:
    run: true